'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Save, ShieldCheck } from 'lucide-react';
const apiUrl=process.env.NEXT_PUBLIC_API_URL||'';
type Settings={maxConcurrency:number;batchSize:number;maxAttempts:number;callingStart:string;callingEnd:string;timezone:string;notificationEmail:string;notificationBcc:string;requireHumanApproval:boolean;respectDoNotCall:boolean};
const initial:Settings={maxConcurrency:3,batchSize:10,maxAttempts:3,callingStart:'09:00',callingEnd:'19:00',timezone:'Europe/Madrid',notificationEmail:'',notificationBcc:'',requireHumanApproval:true,respectDoNotCall:true};
export default function SettingsPage(){const [form,setForm]=useState(initial);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
useEffect(()=>{fetch(`${apiUrl}/api/settings`,{cache:'no-store'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||b.detail);setForm(b.data);}).catch(e=>setMessage(e.message)).finally(()=>setLoading(false));},[]);
async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');try{const r=await fetch(`${apiUrl}/api/settings`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error||b.detail);setForm(b.data);setMessage('Configuración guardada correctamente.');}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.');}finally{setSaving(false);}}
return <div className="p-8"><div className="mb-7"><p className="text-sm font-semibold text-slate-500">Control operativo</p><h2 className="mt-1 text-3xl font-bold">Configuración</h2><p className="mt-2 text-sm text-slate-500">Parámetros seguros para la ejecución de campañas.</p></div>{message&&<div className="mb-5 rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}{loading?<p className="text-sm text-slate-500">Cargando configuración...</p>:<form onSubmit={save} className="grid max-w-5xl gap-6 xl:grid-cols-2">
<Section title="Ritmo de llamadas"><NumberField label="Llamadas simultáneas" value={form.maxConcurrency} min={1} max={10} onChange={v=>setForm({...form,maxConcurrency:v})}/><NumberField label="Tamaño del lote" value={form.batchSize} min={1} max={100} onChange={v=>setForm({...form,batchSize:v})}/><NumberField label="Intentos máximos" value={form.maxAttempts} min={1} max={5} onChange={v=>setForm({...form,maxAttempts:v})}/></Section>
<Section title="Horario de España"><div className="grid grid-cols-2 gap-3"><TextField type="time" label="Desde" value={form.callingStart} onChange={v=>setForm({...form,callingStart:v})}/><TextField type="time" label="Hasta" value={form.callingEnd} onChange={v=>setForm({...form,callingEnd:v})}/></div><p className="text-xs text-slate-500">Zona horaria fija: Europe/Madrid.</p></Section>
<Section title="Notificaciones"><TextField type="email" label="Correo principal" value={form.notificationEmail} onChange={v=>setForm({...form,notificationEmail:v})}/><TextField type="email" label="Copia oculta" value={form.notificationBcc} onChange={v=>setForm({...form,notificationBcc:v})}/></Section>
<Section title="Protecciones obligatorias"><Protection text="Revisión y aprobación humana antes de llamar"/><Protection text="Excluir automáticamente a quien solicite no recibir llamadas"/><div className="rounded-lg bg-emerald-50 p-3 text-xs leading-5 text-emerald-800">Estas protecciones no pueden desactivarse desde el CRM.</div></Section>
<button disabled={saving} className="inline-flex w-fit items-center gap-2 rounded-lg bg-slate-950 px-5 py-3 font-semibold text-white disabled:opacity-50"><Save size={18}/>{saving?'Guardando...':'Guardar configuración'}</button></form>}</div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold">{title}</h3>{children}</section>}
function NumberField({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(v:number)=>void}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input type="number" required min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))} className="w-full rounded-lg border border-slate-300 px-3 py-2.5"/></label>}
function TextField({label,value,type,onChange}:{label:string;value:string;type:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input type={type} required={type==='time'} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2.5"/></label>}
function Protection({text}:{text:string}){return <div className="flex items-center gap-3 rounded-lg border border-emerald-200 px-3 py-2.5 text-sm text-emerald-800"><ShieldCheck size={18}/>{text}</div>}
